language: objective-c
osx_image: xcode9.4
script:
  - xcodebuild clean -project Magnetic.xcodeproj -scheme Magnetic -destination "platform=iOS Simulator,name=iPhone X,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
  - xcodebuild clean -project Magnetic.xcodeproj -scheme Example -destination "platform=iOS Simulator,name=iPhone X,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
